name: Mostrar nombre y apellidos

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: "Introduce tu nombre y apellidos"
        required: true
        default: "Nombre y Apellidos"

jobs:
  imprimir:
    runs-on: windows-latest

    steps:
      - name: Mostrar nombre completo
        run: echo "${{ github.event.inputs.nombre }}"
